spring:
  application:
    name: Brokage Firm Challenge
  datasource:
    url: @db.url@
    username: @db.username@
    password: @db.password@
    driver-class-name: @db.driver@
  jpa:
    hibernate:
      ddl-auto: @spring.jpa.hibernate.ddl-auto@
    properties:
      hibernate:
        dialect: @spring.jpa.properties.hibernate.dialect@
    show-sql: false

server:
  port: 8585
  servlet:
    context-path: /Brokage-Firm-Challenge

sql:
  init:
    mode: always
