spring:
  application:
    name: Order Management
  datasource:
    url: jdbc:postgresql://34.78.64.89:5432/postgres
    username: postgres
    password: Do$_YRtOv]{z<5L>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: false
        show_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


server:
  port: 8585
  servlet:
    context-path: /OrderManagement


